# -*- coding: utf-8 -*-
"""revisi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gC5cJiK5mKXXiLWTxz9yYSJ99vmToJ_K

# ============================================================
# TOPSIS — ANALISIS TREATMENT PALING POPULER
# GREYCLEAN 2026
# ============================================================
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from matplotlib import rcParams
import warnings

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:,.2f}'.format)
pd.set_option('display.width', 120)

plt.style.use('seaborn-v0_8-whitegrid')

rcParams['font.family'] = 'DejaVu Sans'
rcParams['axes.titlesize'] = 14
rcParams['axes.labelsize'] = 11

print('✅ Library berhasil diimport')

"""# ============================================================
# UPLOAD FILE EXCEL
# ============================================================
"""

from google.colab import files

print('📤 Upload file Excel...')
uploaded = files.upload()

nama_file = list(uploaded.keys())[0]

print(f'✅ File berhasil diupload: {nama_file}')

xl = pd.ExcelFile(nama_file)

print('📋 Sheet tersedia:')

for i, s in enumerate(xl.sheet_names, 1):
    print(f'{i}. {s}')

all_data = []

for sheet in xl.sheet_names:

    df_raw = pd.read_excel(
        xl,
        sheet_name=sheet,
        header=None
    )

    df = df_raw.iloc[5:].copy()

    df.columns = [
        'No_Transaksi',
        'Tanggal',
        'Nama_Pelanggan',
        'No_HP',
        'Metode_Pembayaran',
        'Nama_Barang',
        'Tipe_Treatment',
        'Total_Harga'
    ]

    df['Bulan'] = sheet

    df = df[df['No_Transaksi'].apply(
        lambda x: str(x).strip().replace('.0', '').isdigit()
        if pd.notna(x) else False
    )]

    all_data.append(df)

    print(f'✔ {sheet} → {len(df)} transaksi')

df_all = pd.concat(all_data, ignore_index=True)

print(f'Total transaksi: {len(df_all)}')

df_all['Total_Harga'] = pd.to_numeric(
    df_all['Total_Harga'],
    errors='coerce'
)

df_all.dropna(subset=['Total_Harga'], inplace=True)

df_all['Tipe_Treatment'] = (
    df_all['Tipe_Treatment']
    .astype(str)
    .str.strip()
    .str.title()
)

df_all = df_all[
    ~df_all['Tipe_Treatment'].isin(
        ['-', 'Nan', 'None', '']
    )
]

print('✅ Data berhasil dibersihkan')

print(f'Total treatment unik: {df_all["Tipe_Treatment"].nunique()}')

df_matrix = df_all.groupby('Tipe_Treatment').agg(

    C1_Jumlah_Transaksi = (
        'No_Transaksi',
        'count'
    ),

    C2_Total_Pendapatan = (
        'Total_Harga',
        'sum'
    ),

    C3_Pelanggan_Unik = (
        'Nama_Pelanggan',
        'nunique'
    ),

    C4_Rata_Rata_Harga = (
        'Total_Harga',
        'mean'
    )

).reset_index()

df_matrix = df_matrix.sort_values(
    'C1_Jumlah_Transaksi',
    ascending=False
)

display(df_matrix)

bobot = np.array([
    0.35,
    0.35,
    0.20,
    0.10
])

nama_kriteria = [
    'Jumlah Transaksi',
    'Total Pendapatan',
    'Pelanggan Unik',
    'Rata-rata Harga'
]

for nama, b in zip(nama_kriteria, bobot):

    print(f'{nama} = {b}')

X = df_matrix[[
    'C1_Jumlah_Transaksi',
    'C2_Total_Pendapatan',
    'C3_Pelanggan_Unik',
    'C4_Rata_Rata_Harga'
]].values.astype(float)

penyebut = np.sqrt(
    (X**2).sum(axis=0)
)

R = X / penyebut

df_R = pd.DataFrame(
    R,
    columns=['C1', 'C2', 'C3', 'C4'],
    index=df_matrix['Tipe_Treatment']
)

display(df_R.round(4))

V = R * bobot

df_V = pd.DataFrame(
    V,
    columns=['C1', 'C2', 'C3', 'C4'],
    index=df_matrix['Tipe_Treatment']
)

display(df_V.round(4))

A_plus = V.max(axis=0)

A_minus = V.min(axis=0)

print('A+')
print(A_plus)

print('\nA-')
print(A_minus)

D_plus = np.sqrt(
    ((V - A_plus)**2).sum(axis=1)
)

D_minus = np.sqrt(
    ((V - A_minus)**2).sum(axis=1)
)

df_jarak = pd.DataFrame({

    'Treatment':
    df_matrix['Tipe_Treatment'],

    'D+':
    D_plus,

    'D-':
    D_minus

})

display(df_jarak)

Ci = D_minus / (D_plus + D_minus)

df_hasil = pd.DataFrame({

    'Treatment':
    df_matrix['Tipe_Treatment'],

    'Jumlah_Transaksi':
    df_matrix['C1_Jumlah_Transaksi'],

    'Total_Pendapatan':
    df_matrix['C2_Total_Pendapatan'],

    'Pelanggan_Unik':
    df_matrix['C3_Pelanggan_Unik'],

    'Nilai_Preferensi':
    Ci

})

df_hasil['Ranking'] = (
    df_hasil['Nilai_Preferensi']
    .rank(ascending=False)
    .astype(int)
)

df_hasil = df_hasil.sort_values('Ranking')

display(df_hasil)

print('🏆 TOP 5 TREATMENT')

top5 = df_hasil.head(5)

for i, row in top5.iterrows():

    print(
        f'{row["Ranking"]}. '
        f'{row["Treatment"]} '
        f'(Ci = {row["Nilai_Preferensi"]:.4f})'
    )

plt.figure(figsize=(12,7))

plt.barh(
    df_hasil['Treatment'][::-1],
    df_hasil['Nilai_Preferensi'][::-1]
)

plt.xlabel('Nilai Preferensi')

plt.ylabel('Treatment')

plt.title(
    'Ranking Treatment Paling Populer'
)

for i, v in enumerate(
    df_hasil['Nilai_Preferensi'][::-1]
):

    plt.text(
        v + 0.005,
        i,
        f'{v:.3f}',
        va='center'
    )

plt.tight_layout()

plt.show()

plt.figure(figsize=(12,7))

plt.barh(
    df_hasil['Treatment'][::-1],
    df_hasil['Jumlah_Transaksi'][::-1]
)

plt.xlabel('Jumlah Transaksi')

plt.ylabel('Treatment')

plt.title(
    'Jumlah Transaksi per Treatment'
)

plt.tight_layout()

plt.show()

terbaik = df_hasil.iloc[0]

print('='*60)

print('KESIMPULAN ANALISIS')

print('='*60)

print(f'''
Treatment paling populer berdasarkan metode TOPSIS adalah:

🏆 {terbaik["Treatment"]}

Dengan:
- Nilai preferensi : {terbaik["Nilai_Preferensi"]:.4f}
- Jumlah transaksi : {terbaik["Jumlah_Transaksi"]}
- Total pendapatan : Rp {terbaik["Total_Pendapatan"]:,.0f}
- Pelanggan unik   : {terbaik["Pelanggan_Unik"]}

Treatment tersebut menjadi alternatif terbaik
karena memiliki performa tertinggi berdasarkan
seluruh kriteria TOPSIS.
''')